// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdW8Sn-l-EEYQJGW0m5CmJSbndafkFTNY',
    appId: '1:294940490893:web:210856645a2cd3d20936c4',
    messagingSenderId: '294940490893',
    projectId: 'fir-tutorial-81c6c',
    authDomain: 'fir-tutorial-81c6c.firebaseapp.com',
    storageBucket: 'fir-tutorial-81c6c.appspot.com',
    measurementId: 'G-PLEYGY6RSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBKF-xk4Z_ZluDKuyP2aPhDSdXCRE4ok',
    appId: '1:294940490893:android:c9be0200f42412df0936c4',
    messagingSenderId: '294940490893',
    projectId: 'fir-tutorial-81c6c',
    storageBucket: 'fir-tutorial-81c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0k0D5NJxzr-Ragq3iM59i_sUj3rS_Wc',
    appId: '1:294940490893:ios:86ec65629be45c8b0936c4',
    messagingSenderId: '294940490893',
    projectId: 'fir-tutorial-81c6c',
    storageBucket: 'fir-tutorial-81c6c.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0k0D5NJxzr-Ragq3iM59i_sUj3rS_Wc',
    appId: '1:294940490893:ios:9095090b0a509f8b0936c4',
    messagingSenderId: '294940490893',
    projectId: 'fir-tutorial-81c6c',
    storageBucket: 'fir-tutorial-81c6c.appspot.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
